#version 430 core
//#extension GL_ARB_compute_shader : enable
//#extension GL_ARB_shader_storage_buffer_object : enable

layout(std430, binding=0) buffer TestBuffer
{
	vec4 data[];
};

layout(local_size_x = 2, local_size_y = 1, local_size_z = 1) in;
void main(){
	vec4 newShit = vec4(1.0, 1.0, 1.0, 1.0);
	imageStore(test_buffer, int(gl_GlobalInvocationID.x), newShit);
	//dumm.test[gl_GlobalInvocationID.x].xyz = newShit;
}